In [5]:
import numpy as np

In [3]:
heights = [77, 72, 74, 82]

In [4]:
heights * 2.54

TypeError: can't multiply sequence by non-int of type 'float'

In [6]:
np.array(heights)

array([77, 72, 74, 82])

In [7]:
np_heights = np.array(heights)

In [8]:
np_heights * 2.54

array([195.58, 182.88, 187.96, 208.28])

In [9]:
list_1 = [1, 2, 3]
list_2 = [4, 5, 6]

list_1 + list_2

[1, 2, 3, 4, 5, 6]

In [11]:
np_1 = np.array([1, 2, 3])
np_2 = np.array([4, 5, 6])

np_1 + np_2 # sums the elements

array([5, 7, 9])

In [14]:
np.array([1, 2, 3, False])

array([1, 2, 3, 0])

## N Dimensional Arrays